var text="Velociraptor is a genus of herbivorous ceratopsid dinosaur that first appeared during the late Maastrichtian stage of the late Cretaceous period.";
var dinosaur= "triceratops";
var dinosaurUpperCased = dinosaur.toUpperCase();
console.log(dinosaurUpperCased); 
var textAfter = text.replace('Velocitoraptor', 'Triceratops');
console.log(textAfter);
var textSplit = text.split();
console.log(textSplit);
var textJoin = textSplit.join();
console.log(textJoin);
var textHalf = text.length/2;
console.log(textHalf);
